"""auth: user fields, allowed_emails, user_secrets

Revision ID: 615a4bbe8de0
Revises: df58c58a8bf9
Create Date: 2026-06-10 18:07:14.893129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615a4bbe8de0'
down_revision: Union[str, Sequence[str], None] = 'df58c58a8bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_emails',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('invited_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user_secrets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(length=12), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'kind')
    )
    # NOTE: 'strategy_series_time_idx' is created automatically by TimescaleDB's
    # create_hypertable; it is not in our models. Do NOT drop it (autogen false positive).
    op.add_column('users', sa.Column('supabase_uid', sa.String(length=64), nullable=True))
    # Non-null booleans on an existing table need a server_default to backfill rows.
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'supabase_uid')
    op.drop_table('user_secrets')
    op.drop_table('allowed_emails')
    # ### end Alembic commands ###
