"""account: draft_basket for cross-device builder draft

Revision ID: 77fedbe6e435
Revises: 615a4bbe8de0
Create Date: 2026-06-11 00:39:51.153942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77fedbe6e435'
down_revision: Union[str, Sequence[str], None] = '615a4bbe8de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('draft_basket', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # NOTE: 'strategy_series_time_idx' is created by TimescaleDB's create_hypertable, not
    # our models — do NOT drop it (autogen false positive).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'draft_basket')
    # ### end Alembic commands ###
