"""initial schema

Revision ID: df58c58a8bf9
Revises: 
Create Date: 2026-06-10 00:26:06.785489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df58c58a8bf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_usd', sa.Float(), nullable=False),
    sa.Column('start_balance_usd', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('ref', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('underlying', sa.String(length=8), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('entry_margin', sa.Float(), nullable=False),
    sa.Column('margin_badge', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('target_pnl', sa.Float(), nullable=True),
    sa.Column('stop_loss_amount', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct_of_margin', sa.Float(), nullable=True),
    sa.Column('auto_exit', sa.Boolean(), nullable=False),
    sa.Column('auto_exit_suspended', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('underlying', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('contract_value', sa.Float(), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('dte', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('mark_at_entry', sa.Float(), nullable=False),
    sa.Column('spot_at_entry', sa.Float(), nullable=False),
    sa.Column('target_pnl', sa.Float(), nullable=True),
    sa.Column('stop_pnl', sa.Float(), nullable=True),
    sa.Column('auto_exit', sa.Boolean(), nullable=False),
    sa.Column('close_scope', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.Column('exit_gross', sa.Float(), nullable=True),
    sa.Column('exit_fees', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legs_position_id'), 'legs', ['position_id'], unique=False)
    op.create_index(op.f('ix_legs_user_id'), 'legs', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_position_id'), 'notes', ['position_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('strategy_series',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('vega', sa.Float(), nullable=False),
    sa.Column('atm_iv', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('legs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'position_id')
    )
    op.create_index('ix_series_pos_time', 'strategy_series', ['position_id', 'time'], unique=False)
    op.create_index(op.f('ix_strategy_series_user_id'), 'strategy_series', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # Make the 1-min MTM/IV/greeks table a TimescaleDB hypertable (partitioned on time).
    op.execute(
        "SELECT create_hypertable('strategy_series', 'time', if_not_exists => TRUE, migrate_data => TRUE)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_series_user_id'), table_name='strategy_series')
    op.drop_index('ix_series_pos_time', table_name='strategy_series')
    op.drop_table('strategy_series')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_position_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_legs_user_id'), table_name='legs')
    op.drop_index(op.f('ix_legs_position_id'), table_name='legs')
    op.drop_table('legs')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
