"""margin_calibration table

Revision ID: f286e3cd79c0
Revises: 77fedbe6e435
Create Date: 2026-06-11 02:11:00.368150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f286e3cd79c0'
down_revision: Union[str, Sequence[str], None] = '77fedbe6e435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin_calibration',
    sa.Column('underlying', sa.String(length=8), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('samples', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('underlying')
    )
    # 'strategy_series_time_idx' is TimescaleDB's auto hypertable index — not ours; don't drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('margin_calibration')
    # ### end Alembic commands ###
